language: cpp

compiler:
    - g++
before_install:
    - sudo add-apt-repository -y ppa:dhart/ppa
    - sudo apt-get update -q
    - sudo apt-get -y install cxxtest
    - sudo pip install cpp-coveralls
    - export PATH=$PATH:/usr/bin
script:
    - make && bin/runner
after_success:
    - coveralls --exclude lib --exclude tests
